[EVAL_CONFIG]
enabled_metrics = ["faithfulness", "correctness", "retrievability"]

[MODEL_ATLAAI_SELENE_1_MINI_LLAMA_3_1_8B]
model_name = "$SELENE_OPENAI_DEFAULT_MODEL_NAME"
prompt_type = "selene-mini"
regex_type = "re_selene"
temperature = 0.0

[MODEL_WATTELSE_GPT4O_MINI_SWEDEN_DEV]
model_name = "$AZURE_SE_WATTELSE_OPENAI_DEFAULT_MODEL_NAME_DEV"
deployment_type = "cloud"
api_base = "$AZURE_SE_WATTELSE_OPENAI_ENDPOINT_DEV"
api_key = "$AZURE_SE_WATTELSE_OPENAI_API_KEY_DEV"
prompt_type = "vanilla"
regex_type = "default"
temperature = 0.0

[MODEL_DEEPSEEK_AI_DEEPSEEK_R1_DISTILL_LLAMA_8B]
model_name = "$DEEP_OPENAI_DEFAULT_MODEL_NAME"
prompt_type = "deepseek"
regex_type = "re_deepseek"
temperature = 0.0